version: 0.0
os: linux
files:
 - source: /sampleapp/index.html
   destination: /var/www/html/
hooks:
 BeforeInstall:
  - location: /scripts/httpd_install.sh
    timeout: 200
    runas: root
  - location: /scripts/httpd_start.sh
    timeout: 200
    runas: root
 ApplicationStop:
  - location: /scripts/httpd_stop.sh
    timeout: 200
    runas: root

